[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings=["@openzeppelin/upgradeable/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/","@foundry-devops/src/=lib/foundry-devops/src/", "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
fs_permissions=[{access="read-write", path="./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
